version: '3.7'

services:
  nodejs-demo:
    image: nodejsdemo
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: nodejs-demo
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev